apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-plugin
  title: My Backstage Plugin
  description: Custom Backstage plugin package.
  tags:
    - backstage
    - plugin
spec:
  type: library
  lifecycle: experimental
  owner: platform-team
